version: "3.9"
services:
  better-auth-tss:
    image: postgres:17
    restart: always
    container_name: better-auth-tss
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
